name: Cross Repo Access Test
on: 
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: This Repo
        uses: actions/checkout@v4
      
      - run: ls -ltra
      
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "961000"
          private-key: ${{ secrets.REPO_CLONE_ACCESS_TEST_01_2024_08_03_PRIVATE_KEY_PEM }}
          
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          repository: KeivanAshoory/gha-tests-2
          path: that-repo

      - run: ls
      - run: cd that-repo
      - run: ls

          
