name: Deploy

on:
  workflow_call:
  
jobs:
  deploy-job:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy job started."
      - run: echo "Deploy job completed."
